name: build


on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'
    paths:
      - 'Sources/**'
      - 'Examples/**'
      - 'Tests/**'


jobs:
  build:
    uses: madmachineio/actions/.github/workflows/build.yml@main